GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTY0MTkwMDQ3OX0.qeeqZsEZKpAPIjqYIZGZrgZXEKHpZD5zf1-WOk5fx7s

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "Kyle"
}