### add user

POST http://localhost:3000/register
Content-Type: application/json

{
  "email": "user",
  "password": "user"
}

### log user

POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "user",
  "password": "user"
}

### get all users

GET http://localhost:3000/auth-endpoint
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjRkYTQzYmM0YmFiMWVkNzQxN2U0NWQiLCJ1c2VyRW1haWwiOiJ1c2VyIiwiaWF0IjoxNjQ5MzE3MzM5LCJleHAiOjE2NDk0MDM3Mzl9.rb_rrtHvVxFXRa_FdUAwF2InJegLjWRqan51kbxT8Us